name: SonarQube Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=main --cov-report=xml

      # --- 💡 진단 단계 추가 ---
      - name: Display coverage report content
        run: |
          echo "--- Content of coverage.xml ---"
          cat coverage.xml
          echo "--------------------------------"

      # 기존 SonarQube 분석 단계
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
