name: SonarQube Analysis

on:
  # main 브랜치에 코드가 push될 때마다 이 워크플로우를 실행합니다.
  push:
    branches:
      - main
  # Pull Request를 직접 테스트하고 싶을 때 아래 주석을 해제하세요.
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # SonarQube의 blame 정보를 위해 전체 git 히스토리를 가져옵니다.
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
